[package]
name = "webserver"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.85"
futures = "0.3.31"
pin-project-lite = "0.2.16"
tokio = { version = "1.43.0", features = ["full"] }
